# Generated by Django 4.2 on 2025-02-26 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_column='contract_number', max_length=100)),
                ('client_name', models.CharField(db_column='client_name', max_length=100)),
                ('otr', models.IntegerField(db_column='otr')),
            ],
            options={
                'db_table': 'contract_client',
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_installment', models.IntegerField(db_column='number_installment')),
                ('total_installment', models.IntegerField(db_column='total_installment')),
                ('due_date', models.DateField(db_column='due_date')),
                ('contract_number', models.ForeignKey(db_column='contract_number', on_delete=django.db.models.deletion.CASCADE, to='api_app.contractclient')),
            ],
            options={
                'db_table': 'installment',
            },
        ),
    ]
