# Generated by Django 4.2 on 2025-02-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractclient',
            name='monthly_installment',
            field=models.IntegerField(blank=True, db_column='monthly_installment', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='contractclient',
            name='client_name',
            field=models.CharField(blank=True, db_column='client_name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractclient',
            name='contract_number',
            field=models.CharField(blank=True, db_column='contract_number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contractclient',
            name='otr',
            field=models.IntegerField(blank=True, db_column='otr', null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='contract_number',
            field=models.ForeignKey(blank=True, db_column='contract_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.contractclient'),
        ),
        migrations.AlterField(
            model_name='installment',
            name='due_date',
            field=models.DateField(blank=True, db_column='due_date', null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='number_installment',
            field=models.IntegerField(blank=True, db_column='number_installment', null=True),
        ),
        migrations.AlterField(
            model_name='installment',
            name='total_installment',
            field=models.IntegerField(blank=True, db_column='total_installment', null=True),
        ),
        migrations.CreateModel(
            name='ContractCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OTR', models.IntegerField(blank=True, db_column='otr', null=True)),
                ('DP', models.IntegerField(blank=True, db_column='dp', null=True)),
                ('range_date', models.IntegerField(blank=True, db_column='range_date', null=True)),
                ('contract_number', models.ForeignKey(blank=True, db_column='contract_number', null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.contractclient')),
            ],
            options={
                'db_table': 'contract_calculation',
            },
        ),
    ]
