# Generated by Django 4.2 on 2025-02-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_contractclient_monthly_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractclient',
            name='dp',
            field=models.IntegerField(blank=True, db_column='dp', null=True),
        ),
        migrations.AddField(
            model_name='contractclient',
            name='range_date',
            field=models.IntegerField(blank=True, db_column='range_date', null=True),
        ),
        migrations.DeleteModel(
            name='ContractCalculation',
        ),
    ]
